In [1]:
import numpy as np


In [3]:
a = np.array([[1,2,3],[2,3,4]])

In [4]:
print(a)

[[1 2 3]
 [2 3 4]]


In [6]:
a.shape

(2, 3)

In [7]:
a.reshape

<function ndarray.reshape>

In [8]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
a[1:1]

array([], shape=(0, 3), dtype=int64)

In [10]:
a[1,1]

3

In [11]:
a = np.floor(10*rg.random((3,4)))

NameError: name 'rg' is not defined

In [16]:
import numpy as np

rg = np.random.default_rng()
a = np.floor(10 * rg.random((3, 4)))

In [17]:
a

array([[2., 5., 5., 8.],
       [4., 7., 2., 6.],
       [8., 5., 9., 7.]])